language: julia

os:
  - osx

julia:
  - 0.6

matrix:
  allow_failures:
    julia: nightly

notifications:
  email: false

branches:
  only:
  - master

after_success:
  - julia -e 'using Pkg; Pkg.add("Documenter"); cd(Pkg.dir("ABC")); include(joinpath("docs", "make.jl"))'
  - julia -e 'using Pkg; cd(Pkg.dir("Distributions")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(process_folder())'

